name: Matrix
on: pull

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
        include:  # sets a variable for this configuration called is_ubuntu_8
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true" 
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
      fail-fast: true
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node_version }}
